### PR TITLE
Script to read data from csv File

### PR DESCRIPTION
**Pull request by DaviKaur**

### CODE REVIEW

**Comment by mandeeps708** [comment]
Needed to be squashed into one commit.

**Comment by amarjeetkapoor1** [comment]
@GreatDevelopers/coreowners  @GreatDevelopers/basher Any review related to this pull request I believe If the issues is just related to squashing the commits it can be done while merging the pull request

**Comment by amarjeetkapoor1** [comment]
Ping !

**Comment by mandeeps708** [comment]
Alright!

**Pull request merged**
